[package]
name = "githome"
version = "0.1.0"
authors = ["Benedikt Mandelkow <benedikt.mandelkow@rwth-aachen.de>"]
edition = "2018"
publish = false

[dependencies]
git2 = "*"
serde = "*"
docopt = "*"
structopt = "*"


[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
